config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
    end

    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        
        if @category.save
            flash[:notice] = 'Category has been created.'
            redirect_to @category
        else
            flash.now[:alert] = "Category has not been created."
            render "new"
        end
        
    end

    def show
        @category = Category.find(params[:id])
    end
    

    private

    def category_params
        params.require(:category).permit(:name)
    end    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<%= link_to "New Category", new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_for(@category) do |f| %>
    <% if @category.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %>
    prohibited this category from being saved:</h2>

    <ul>
        <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
    <% end %>
   <p>
   <%= f.label :name %>
   <%= f.text_field :name %>
   </p>

   <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bazar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <% flash.each do |key, message| %>
     <div><%= message %></div>
  <% end %>
  
    <%= yield %>
  </body>
</html>